### ISSUE TITLE
Hub information is incorrect

### ISSUE THREAD

**Issue by jcustenborder** [jcustenborder/kafka-config-provider-vault#2]

**Comment by Kalyan-D** [comment]
Hello jcustenborder ,

I have configured my confluent worker with following properties:

config.providers.vault.param.vault.token=************************
config.providers.vault.class=com.github.jcustenborder.kafka.config.vault.VaultConfigProvider
config.providers.vault.param.vault.address=http://********:8200
config.providers=vault
config.providers.vault.param.vault.login.by=Token


and started the worker in distributed mode

I have configured my source connection with the following configs

{
  "name": "inventory-connector",
  "config": {
    "connector.class": "io.debezium.connector.mysql.MySqlConnector",
    "tasks.max": "1",
    "database.hostname": "*******",
    "database.port": "3306",
    "database.user": "${vault:confluent/secrets:mysqluser}",
    "database.password": "${vault:confluent/secrets:mysqlpass}",
    "database.server.id": "184055",
    "database.server.name": "dbserver2",
    "database.include.list": "inventory",
    "database.history.kafka.bootstrap.servers": "localhost:9092",
    "database.history.kafka.topic": "schema_changes.inventory"
  }
}


In the Hashicorp vault, I have stored the secrets in the following path
confluent/secret

But while running source connector with rest call I'm getting the following error
**{"error_code":500,"message":"Vault path 'confluent/secrets' was not found"}**

**Comment by jcustenborder** [comment]
@Kalyan-D This looks incorrect.
```
"database.user": "${vault:confluent/secrets:mysqluser}",
"database.password": "${vault:confluent/secrets:mysqlpass}",
```
try 
```
"database.user": "${vault:secret/confluent:mysqluser}",
"database.password": "${vault:secret/confluent:mysqlpass}",
```

**Comment by Kalyan-D** [comment]
Hello,

In the Hashicorp vault, I have stored the secrets in the following path

confluent/secrets.
That is why I have provided the path in that manner.

**Comment by Kalyan-D** [comment]
[image: image.png]


Please find the snap.

Thanks & Regards

**Comment by jcustenborder** [comment]
Then you might want to try secret/confluent/secrets. That error message is coming from vault it's self.

**Comment by Kalyan-D** [comment]
I have tried even that way but still facing same issue

{"error_code":500,"message":"Vault path 'secret/confluent/secrets' was not found"}
