### ISSUE TITLE
is the project abandoned?

### ISSUE THREAD

**Issue by eliax1996** [jcustenborder/kafka-config-provider-vault#8]

**Comment by jcustenborder** [comment]
@eliax1996 It has not been a priority. I have created another version of this project that the CSID Team @ Confluent is maintaining. It took a while to iron this out. The new project is available [here](https://github.com/confluentinc/csid-secrets-providers/)

**Comment by eliax1996** [comment]
Thank you, nice to know that the project scope has been expanded!
So the suggestion is to switch to the other project.

Anyway, the AppRole auth mode that I created an mr for is working in aws, probably isn't elegant but works :) 
I think has no more value or sense to merge since the new project seems to already have the RoleBased auth.

Thank you for the reply!
Appreciated
